import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const read = path => readFileSync(new URL('../'+path, import.meta.url),'utf8');
const events = new Map();
const sizeWrap = {classList:{toggle(){}}, innerHTML:'',querySelector(selector){return {addEventListener(type, fn){events.set(selector,fn);}};}};
const context = vm.createContext({window:{addEventListener(){}},localStorage:{getItem(){return null;},setItem(){}},document:{head:{appendChild(){}},getElementById(id){return id==='size'?sizeWrap:{style:{},classList:{add(){},remove(){}},value:'portrait character'};},createElement(){return {textContent:'',get innerHTML(){return this.textContent;}};}},lucide:{createIcons(){}},tr:k=>k,alert:msg=>{throw Error(msg);},uploadedNames:{1:'landscape.png',2:'',3:''},CLIENT_ID:'test'});
vm.runInContext(read('static/js/cli-image-tools.js'),context);
const control = context.window.StudioCliImageTools.createSizeControl({wrapId:'size',storageKey:'test'});
control.setActive(true);
control.setSourceDimensions(1600,900);
events.get('[data-size-ratio]')({currentTarget:{value:'story'}});
assert.equal(control.value(),'576x1024');
control.setSourceDimensions(1920,1080);
assert.equal(control.value(),'576x1024','new reference must not override selected portrait ratio');
context.cliSizeControl=control;
const html=read('static/klein.html');
const start=html.indexOf('async function submitLocal()');
vm.runInContext(html.slice(start,html.indexOf('async function submitCli()',start)),context);
let body;
context.fetch=async(url,options)=>{body=JSON.parse(options.body);return {json:async()=>({})};};
await vm.runInContext('submitLocal()',context);
assert.deepEqual(body.params['156'],{width:576,height:1024});
assert.deepEqual(body.params['152'],{width:576,height:1024});
assert.equal(body.params['278'].image,'landscape.png');
const workflow=JSON.parse(read('workflows/Flux2-Klein.json'));
assert.equal(workflow['156'].class_type,'EmptyFlux2LatentImage');
assert.equal(workflow['152'].class_type,'Flux2Scheduler');
console.log('Klein portrait output overrides both generation nodes and preserves reference image');
